'use strict';

module.exports = {
  config: {
    css: '',
    termCSS: '',
    updateChannel: 'stable',
    fontSize: 14,
    fontFamily:
      '"RobotoMono Nerd Font", "Roboto Mono", Consolas, Menlo, monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1.2,
    cursorColor: '#cccccc',
    cursorAccentColor: '#000',
    cursorShape: 'BEAM',
    cursorBlink: true,
    foregroundColor: '#cccccc',
    backgroundColor: '#000',
    selectionColor: '#3B3E46',
    borderColor: '#191919',
    padding: '2px 6px 6px 14px',
    colors: {
      black: '#000',
      lightBlack: '#808080',
      red: '#EB543B',
      lightRed: '#EB543B',
      green: '#1DFF5C',
      lightGreen: '#1DFF5C',
      blue: '#009DFF',
      lightBlue: '#009DFF',
      yellow: '#FF9900',
      lightYellow: '#FF9900',
      magenta: '#E339DD',
      lightMagenta: '#E339DD',
      cyan: '#00FFF0',
      lightCyan: '#00FFF0',
      white: '#CCCCCC',
      lightWhite: '#fff',
    },
    shell: 'zsh',
    shellArgs: ['--login'],
    env: {},
    bell: false,
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    webLinksActivationKey: 'Command',
    disableLigatures: true,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
  },

  plugins: ['hypercwd', 'hyper-hide-title'],

  localPlugins: [],
  keymaps: {},
};
