pcall(require, "plugins-setup")

pcall(require, "core.options")
pcall(require, "core.keymaps")
pcall(require, "core.colorscheme")

pcall(require, "plugins.comment")
pcall(require, "plugins.prettier")
pcall(require, "plugins.nvim-tree")
pcall(require, "plugins.lualine")
pcall(require, "plugins.telescope")
pcall(require, "plugins.autopairs")
pcall(require, "plugins.treesitter")
pcall(require, "plugins.gitsigns")
pcall(require, "plugins.mason")
pcall(require, "plugins.cmp")
pcall(require, "plugins.lspconfig")
pcall(require, "plugins.null-ls")
pcall(require, "plugins.rust")
